# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=225, validators=[django.core.validators.EmailValidator])),
                ('photo', models.ImageField(blank=True, upload_to=b'')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('company_name', models.CharField(blank=True, default='', max_length=60)),
                ('company_to_visit', models.CharField(blank=True, default='', max_length=60)),
                ('employee_to_visit', models.CharField(blank=True, default='', max_length=60)),
                ('subscribe_to_mailing_list', models.BooleanField(default=False)),
            ],
        ),
    ]
